Scan to Folder #805 error on MACOS\n-\nCould not send to the SMB server because there was insufficient free space on the server side.: {class: note}
classes: {
    step: {shape: rectangle}
    diagnose: {shape: diamond}
    fixed: {shape: rectangle; style: {fill: "#90FF90"; stroke: "#00A000";}}
    failure: {shape: rectangle; style: {fill: "#FF9090"; stroke: "#A00000";}}
    note: {shape: page;}
}

1: SMB Server has ran out of storage. {class: fixed}
